## ABOUT NUMPY

- use fixed type (as dtype=float64)
- is faster than lists
- SIMD (Single Instruction, Multiple Data) vector processing

### The Basics

In [ ]:
import numpy as np
a = np.array([1,2,3], dtype='int32') #par default int64
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

In [ ]:
print("Get Dimension")
print(a.ndim)
print("Get Shape")
print(b.shape)
print("Get Type")
print(a.dtype) 
print("Get Size")
print(a.itemsize) # size one element in array in bytes
print("Get total size")
print(a.nbytes) # size of the entire array in bytes
print("Get number of elements")
print(a.size) # the number of the elements

In [ ]:
ar = np.array([1,2,3,4])
br = np.ones((1, 4))
M = np.outer(a, b)
d = np.diag(M)
t = np.trace(M)

### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
# Get a specific element [r, c]
a[1, 5]
# Get a specific row 
a[0, :]
# Get a specific column
a[:, 2]
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

a[1,5] = 20

a[:,2] = [1,2]
print(a)

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3d matrix
print(b)

b[0,1,1] # a specific element (work outside in)

# b[:,1,:] = [[9,9,9],[8,8]] # replace, error
b[:,1,:] = [[9,9], [8,8]] # replace 
print(b)

### Initializing Different Types of Arrays

In [ ]:
np.zeros((2,3)) # All 0s matrix
np.ones((4,2,2), dtype='int32') # All 1s matrix (3d matrix)
np.full((2,2), 99) # Any other number
np.full_like(a, 4) # Any other number (full_like)
np.random.rand(4,2) # Random decimal numbers
np.random.randint(-4,8, size=(3,3)) # Random Integer values
np.identity(5) # The identity matrix

In [ ]:
np.ones((4,2,2), dtype='int32') # All 1s matrix

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

# axis=0 - to repeat rows
# axis=1 - to repeat collums

#slices
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100 #doesnt change the value of the matrix a

print(a)

### Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

a = a + 2
print(a)

a = a - 2
print(a)

a = a * 2
print(a)

a = a / 2
print(a)

a = a ** 2
print(a)


In [ ]:
b = np.array([1,0,1,0])
d = a + b
print(d)

c = np.array([1, 0, 1])
# f = a + c # error

##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

d = np.matmul(a,b)  # matrix multiplication
print(d)

c = np.identity(3)
np.linalg.det(c) # the determinant

In [ ]:
A = np.identity(4)
b = np.array([0, 1, 2, 3])
np.trace(A) # sum of the diagonal values
np.linalg.eig(A) # Eigenvalues / Eigenvectors
np.linalg.inv(A)
np.linalg.norm(A)
np.linalg.matrix_rank(A)
np.linalg.solve(A,b) # Solve linear system


##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])

np.min(stats, axis=0) # min in every collumn
                      # axis 0  ↓
                      # axis 1  →
np.min(stats, axis=1)
np.min(stats)

np.max(stats, axis=0) 
np.max(stats, axis=1)
np.max(stats) 

np.sum(stats, axis=0)
np.sum(stats, axis=1)
np.sum(stats)

##### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after1 = before.reshape((1,8)) 
print(after1)

after2 = before.reshape((8,1)) 
print(after2)

after3 = before.reshape((4,2)) 
print(after3)

# after4 = before.reshape((2,2)) # error

after5 = before.reshape((2,2,2)) # 3D matrix
print(after5)

# after6 = before.reshape((2,3)) # error

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2]) # Vertically stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
# print(h1)
# print(h2)

np.hstack((h1,h2)) # Horizontal  stack

##### Load Data from File

In [44]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [45]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])